### ISSUE TITLE
COM真空包重测发料 #W050

### ISSUE THREAD

**Issue by guozhangluo** [guoxunbo/client#104]
扫描真空包号自动与ERP订单自动匹配，如果符合的订单有多条默认选中第一条
![image](https://user-images.githubusercontent.com/55224413/67822939-215daa80-fafc-11e9-8020-1ce280e989ed.png)
验证匹配箱号的订单信息，默认选择第一条
![image](https://user-images.githubusercontent.com/55224413/67823015-68e43680-fafc-11e9-8786-f19fe7ec1ba9.png)

**Comment by guoxunbo** [comment]
这个以前讨论过这么做，但是GC进行否决了。需要和小星一起看下这个需求。
就是扫描之后，自动匹配ERP的单据，进行发货或者重测。但是GC那时候否决此种需求了。
